modLoader = "javafml"
loaderVersion = "[2,)"
license = "MIT"

[[mods]]
modId = "advanced_accessory_system"
version = "${version}"
displayName = "Advanced Accessory System"
authors = "Alonie"
description = "Allows non-standard items to be placed in the player helmet slot."
mixins = ["advanced_accessory_system-common.mixins.json"]

[[dependencies.advanced_accessory_system]]
modId = "neoforge"
mandatory = true
versionRange = ">=21.11"
ordering = "NONE"
side = "BOTH"

[[dependencies.advanced_accessory_system]]
modId = "minecraft"
mandatory = true
versionRange = ">=1.21.11"
ordering = "NONE"
side = "BOTH"

[[dependencies.advanced_accessory_system]]
modId = "architectury"
mandatory = true
versionRange = ">=19"
ordering = "AFTER"
side = "BOTH"
